style_edition = "2024"

hard_tabs = false
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
struct_variant_width = 0
tab_spaces = 4

# Don't let rustfmt touch imports as long as group_imports and imports_layout
# are not stable.
reorder_imports = false

# Features not available in stable channel:
# group_imports = "StdExternalCrate"
# imports_layout = "HorizontalVertical"
# trailing_comma = "Vertical"
# wrap_comments = true
