[toolchain]
channel = "1.88.0"
profile = "minimal"
components = [
    "clippy",
    "rust-analyzer",
    "rust-src",
    "rustfmt",
]
targets = [
    "riscv32imc-unknown-none-elf",
    "riscv32imac-unknown-none-elf",
]