[target.riscv32imc-unknown-none-elf]
runner = [ "sh", "run.sh" ]

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = false
incremental      = false
opt-level        = 3
lto = 'fat'
overflow-checks  = false
