apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: wasmbed

servers: 1

image: rancher/k3s:v1.33.2-k3s1

options:
  k3d:
    wait: true
    disableLoadbalancer: true
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
