[package]
name = "wasmbed-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]

[dependencies.minicbor]
version = "0.26.2"
default-features = false

[dependencies.uuid]
version = "1.16.0"
default-features = false
features = [ "v4" ]

[features]
serde = [ "dep:serde", "uuid/serde" ]
schemars = [ "dep:schemars", "dep:serde_json" ]

[dependencies.schemars]
version = "0.8.22"
optional = true

[dependencies.serde]
version = "1.0.219"
features = [ "derive" ]
optional = true

[dependencies.serde_json]
version = "1.0.140"
optional = true

[dev-dependencies]

[dev-dependencies.minicbor]
version = "0.26.2"
features = [ "alloc" ]
